### PR TITLE
Add DefaultAzureIdentity support

### LINKED ISSUE #140: Blobs persistance needs support for DefaultAzureCredential()
Connection string isn't enough when it comes to Azure Blob Storage as for security it needs to be able to run using DefaultAzureCredential() in order to delegate access to managed identity

Maybe just adding an extra param in app.conf in the connection section as boolean which in turns this will indicate to the constructor to pass DefaultAzureCredential() as the second parameter for the connection function

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #140

### CODE REVIEW

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
Can you add documentation to the README demonstrating how to use this? Along with all of the other new HOCON settings we introduced in this change thus far?

**Comment by Arkatufus** [comment]
Will do

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by sainzg** [comment]
Quick question all blob storage is via hocon config and how does this get setup when the class inheriting from ReceivePersistentActor only sets the plugin id to use  SnapshotPluginId = $"akka.persistence.snapshot-store.{blobName}";?

Is there a way in the constructor of the inherited class to provide this AzureBlobSnapshotSetup.Create(new Uri(blobConnection), new DefaultAzureCredential());?

**Comment by sainzg** [comment]
Getting this error when the connection is development and nothing is setup to run on azure

akka.persistence.snapshot-store.tester#1153123657]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object
 at Akka.Persistence.Azure.Snapshot.AzureBlobSnapshotStore.InitCloudStorage(Int32 remainingTries)

**Comment by Arkatufus** [comment]
`AzureBlobSnapshotSetup` is ment to be used in conjunction with `ActorSystemSetup` to provide a programatic way of setting up an `ActorSystem`, basically, you can think of `AzureBlobSnapshotSetup` as an override to the standard HOCON configuration. 

When you use `AzureBlobSnapshotSetup` to set up the actor system, it will be automatically injected into the `AzureBlobSnapshotStore` instance furing run-time to override the connection string setting, using the new `DefaultAzureCredential` as a mean to obtain access token to access the Blob Storage resource instead.

Any plugin id that uses the class `"Akka.Persistence.Azure.Snapshot.AzureBlobSnapshotStore, Akka.Persistence.Azure"` will automatically use this overidden value, but there can only be one override, all of them will use the same `DefaultAzureCredential`

**Comment by Aaronontheweb** [comment]
> Quick question all blob storage is via hocon config and how does this get setup when the class inheriting from ReceivePersistentActor only sets the plugin id to use SnapshotPluginId = $"akka.persistence.snapshot-store.{blobName}";?

Your persistent actor is what's setting the `SnapshotPluginId`? That's unsupported and AFAIK, shouldn't even work. Can you post your source (sanitized) and configuration?

**Comment by sainzg** [comment]
SnapshotPluginId works just fine, the problem is when using the exact same config as before but upgrade the package to this version it stops working, not even attempting to use azure just local...

**Pull request merged**
