### PR TITLE
Completed implementation

### PR DESCRIPTION
**Pull request by kaleho**
@Aaronontheweb This is the completed branch I mentioned. I am attaching a capture of the tests as well as the output of the failed tests. As I mentioned the two tests fail when the entire group is run but if I run individually they pass.

Hope that makes sense.

Snippet-TestResults_TwoFailing_20190913
Snippet-TestResults_Passing_20190913

[ReadJournal_CurrentEventsByPersistenceId_should_return_empty_stream_for_cleaned_journal_from_0_to_MaxLong.txt](https://github.com/petabridge/Akka.Persistence.Azure/files/3612041/ReadJournal_CurrentEventsByPersistenceId_should_return_empty_stream_for_cleaned_journal_from_0_to_MaxLong.txt)
[ReadJournal_CurrentEventsByPersistenceId_should_return_remaining_values_after_partial_journal_cleanup.txt](https://github.com/petabridge/Akka.Persistence.Azure/files/3612042/ReadJournal_CurrentEventsByPersistenceId_should_return_remaining_values_after_partial_journal_cleanup.txt)

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@kaleho looks great - I'll review it as soon as I can.

**Comment by Aaronontheweb** [comment]
Looks like we have a couple of merge conflicts here since I merged in your other PR @kaleho - I'll try to get these fixed myself today, but if you can beat me to the punch I'd appreciate it. Once those are in I'll release this to NuGet.

**Comment by kaleho** [comment]
@aaronontheweb I will try and take care of it tonight.

**Comment by kaleho** [comment]
I kdiff'ed the files and re-ran the tests. I think it is good now.

**Comment by Aaronontheweb** [comment]
@kaleho thanks, I'll review it.

**Comment by Aaronontheweb** [comment]
LGTM - going to pull down the source and do some more tweaks before we do a release. Great work @kaleho

**Pull request merged**
